const AuthActionTypes = {

  LOGIN_WITH_INSTAGRAM: 'LOGIN_WITH_INSTAGRAM',
  LOGIN_WITH_INSTAGRAM_SUCCESS: 'LOGIN_WITH_INSTAGRAM_SUCCESS',
  LOGIN_WITH_INSTAGRAM_FAILURE: 'LOGIN_WITH_INSTAGRAM_FAILURE'

};

export default AuthActionTypes;
